config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/sign-in', to: 'sessions#new'
  post '/sign-in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #omniauth
  get '/auth/facebook/callback', to: 'sessions#create'

  get '/sign-up', to: 'users#new'
  resources :users
  resources :weights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    attr_accessor :remember_token
  end

  # Remembers a user in db for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forget a user using cookies
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if given token matches the digest
  def authenticated_cookie?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  module ClassMethods
    # Returns hash digest of given string
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?   BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Tokenable

  has_many :weights

  # Defaults to :user => 1 in db
  enum role: [:admin, :user, :member]

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


  has_secure_password
  validates :password, length: { minimum: 6 }

end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true, numericality: true
  validates :amount, presence: true, numericality: true
  validates :date, presence: true

  default_scope { order(date: :desc) }

  #weights from today, don't use 1.day.ago ase it adds in timestamp
  scope :today, -> { where('date >= ?', (Date.today -1)) }

  # Most date functions start the week on monday (weird)
  scope :weekly, -> { where('date >= ?', 1.week.ago) }
  scope :monthly, -> { where('date >= ?', 1.month.ago) }

  # more control of individual time frame
  scope :created_after, ->(time) { where('date >= ?', time) if time.present? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  include SessionsHelper

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :force_no_login, only: [:new]

  # Login form
  def new
  end

  def create
    #onmiauth Login
    if !auth.nil?
      user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.email = auth['info']['email']
        # generate random password
        u.password = User.new_token
      end
      if user
        log_in user
        flash.now[:notice] = "Welcome #{user.try(:email)}"
        redirect_to root_path
      else
        redirect_to root_path
      end
    else
      # normal session login
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        #set or forget persistant cookie token
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to root_path
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render :new
      end
    end
  end

  # Only log_out if logged in else you get bugs from multiple browser sessions open
  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

  private

  # Omniauth hash
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:new, :create]
  before_action :force_no_login, only: [:new]
  before_action :authorize_user, except: [:index, :new, :create]

  def index
    @users = User.all
    authorize @users
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #send verification email
      UserMailer.verification_email(@user).deliver_later
      #login user after creating them
      log_in @user
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "User updated sucessfully!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password
    )
  end

  def authorize_user
    authorize @user
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController

  before_action :set_weight, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!

  def index
    @weights = @current_user.weights
    respond_to do |f|
      f.html{ }
      f.json{ render json: @weights }
    end

  end

  def show
  end

  def new
    @weight = Weight.new(user_id: current_user.id, date: Time.now.utc)
  end

  def create
    @weight = Weight.new(weight_params)
    if @weight.save
      redirect_to weights_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @weight.update(weight_params)
      redirect_to weights_path
    else
      render :edit
    end
  end

  def destroy
    @weight.destroy if @weight
    redirect_to weights_path
  end


  private

  def set_weight
    @weight = Weight.find_by(user_id: params[:user_id], id: params[:id])
  end

  def weight_params
    params.require(:weight).permit(
      :user_id,
      :amount,
      :date
    )
  end

  def authorize
    authorize @weight
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in given user by setting session key
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in persistent session
  def remember(user)
    user.remember
    # cookie is encrypted and expires in 20 years
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any) else null
  def current_user
    #@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    # first check for user by session
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)

    # if no session, check for cookie with digest token
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated_cookie?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Forgets a persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out given user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Page access requires logged-in user else redirects to login page
  def authenticate!
    if !logged_in?
      flash.now[:notice] = 'Page access requires you to log in'
      redirect_to sign_in_path
    end
  end

  # Force user to not be logged_in to view page (signin/signup)
  def force_no_login
    if logged_in?
      redirect_to root_path, notice: 'You are already logged in'
    end
  end
end

app/views/layouts/application.html.erb
<!doctype html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= yield(:title) %>TWMLS</title>
<%= render 'layouts/metatags/defaultmeta' %><%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application' %>
</head><body class="<%= controller_name %> <%= action_name %>">
    <%= render 'shared/alert_messages' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js'></script>
</body></html>

app/views/layouts/metatags/_defaultmeta.html.erb
<% if content_for?(:description) %>
  <meta name="description" content="<%= yield(:description) %>">
<% end %>
<% if content_for?(:keywords) %>
  <meta name="keywords" content="<%= yield(:keywords) %>">
<% end %>
<% #https://dev.twitter.com/cards/markup %>
<% if content_for?(:twitter) %>
<% end %>
<% #https://developers.facebook.com/docs/sharing/webmasters %>
<% if content_for?(:facebook) %>
<% end %>

app/views/shared/_alert_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(target.errors.count, 'error') %>
    </div>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_userform.html.erb
<%= form_for(@user, url: users_path) do |f| %>

<%= render partial: 'shared/error_messages', locals: { target: @user } %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'userform' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user-info">
      <h1>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>

app/views/weights/index.html.erb
<%= link_to 'Log Weight', new_weight_path %>
<div class="chart-holder"><canvas id="myChart" width="640" height="480"></canvas></div>
<ul>
  <% if !@weights.blank?%>
    <% @weights.each do |w| %>
      <li><%= w.date.strftime('%b %e %l:%M %p') %> - <%= w.amount %></li>
    <% end %>
  <% else %>
    <li>No Weights Yet</li>
  <% end %>
</ul>

app/views/weights/new.html.erb
<%= form_for @weight do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.label :amount %>
  <%= f.number_field :amount, step: '0.01' %>
  <%= f.label :date %>
  <%= f.datetime_field :date %>
  <%= f.submit %>
<% end %>

app/views/welcome/home.html.erb
homepage

<% if logged_in? %>
  <%= link_to 'Log out', logout_path, method: :delete %>
  Welcome <%= link_to current_user.try(:email), user_path(current_user) %>
<% else %>
  <%= link_to 'Sign in', sign_in_path %>
  <%= link_to 'Sign up', sign_up_path %>
<% end %>